## Immoeliza project

### Import of the necessary library

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

pd.options.display.max_colwidth=150

In [2]:
data = pd.read_json('final_dataset_to_clean.json')

In [3]:
data.shape

(118714, 32)

In [4]:
data.head()

,Url,BathroomCount,BedroomCount,ConstructionYear,Country,District,Fireplace,FloodingZone,Furnished,Garden,...,RoomCount,ShowerCount,StateOfBuilding,SubtypeOfProperty,SurfaceOfPlot,SwimmingPool,Terrace,ToiletCount,TypeOfProperty,TypeOfSale
2,https://www.immoweb.be/en/classified/apartment/for-sale/zeebrugge/8380/10957010,1.0,1,1969.0,Belgium,Brugge,NaN,None,NaN,NaN,...,1.0,0.0,GOOD,flat_studio,NaN,NaN,1.0,1.0,2,residential_sale
6,https://www.immoweb.be/en/classified/house/for-sale/tournai/7500/10956841,6.0,13,1920.0,Belgium,Tournai,NaN,None,0.0,NaN,...,31.0,NaN,GOOD,apartment_block,130.0,NaN,NaN,5.0,1,residential_sale
8,https://www.immoweb.be/en/classified/house/for-sale/blankenberge/8370/10956807,2.0,4,2008.0,Belgium,Brugge,NaN,NON_FLOOD_ZONE,1.0,NaN,...,NaN,0.0,GOOD,house,0.0,NaN,NaN,2.0,1,residential_sale
10,https://www.immoweb.be/en/classified/house/for-sale/de-panne/8660/10956664,1.0,4,NaN,Belgium,Veurne,NaN,None,NaN,1.0,...,NaN,NaN,TO_BE_DONE_UP,house,170.0,0.0,1.0,2.0,1,residential_sale
11,https://www.immoweb.be/en/classified/apartment/for-sale/hasselt/3500/10956668,0.0,2,1972.0,Belgium,Hasselt,NaN,NON_FLOOD_ZONE,NaN,NaN,...,1.0,0.0,AS_NEW,apartment,NaN,NaN,1.0,1.0,2,residential_sale

,Url,BathroomCount,BedroomCount,ConstructionYear,Country,District,Fireplace,FloodingZone,Furnished,Garden,...,RoomCount,ShowerCount,StateOfBuilding,SubtypeOfProperty,SurfaceOfPlot,SwimmingPool,Terrace,ToiletCount,TypeOfProperty,TypeOfSale
181788,https://www.immoweb.be/en/classified/house/for-sale/aalter/9880/11425357,1.0,3,2024.0,Belgium,Gent,NaN,None,NaN,1.0,...,4.0,NaN,GOOD,house,234.0,NaN,NaN,0.0,1,residential_sale
181789,https://www.immoweb.be/en/classified/house/for-sale/antwerpen/2020/11370107,4.0,4,NaN,Belgium,Antwerp,NaN,None,0.0,NaN,...,NaN,NaN,JUST_RENOVATED,apartment_block,202.0,NaN,NaN,NaN,1,residential_sale
181790,https://www.immoweb.be/en/classified/apartment/for-sale/antwerpen/2140/11485314,1.0,2,NaN,Belgium,Antwerp,NaN,NON_FLOOD_ZONE,NaN,NaN,...,NaN,NaN,GOOD,apartment,NaN,0.0,1.0,1.0,2,residential_sale
181791,https://www.immoweb.be/en/classified/apartment/for-sale/brugge/8000/11485038,1.0,2,NaN,Belgium,Brugge,NaN,POSSIBLE_FLOOD_ZONE,NaN,NaN,...,8.0,NaN,None,apartment,NaN,NaN,1.0,NaN,2,residential_sale
181792,https://www.immoweb.be/en/classified/apartment/for-rent/woluwe-saint-lambert/1200/11370116,2.0,3,NaN,Belgium,Brussels,NaN,NON_FLOOD_ZONE,NaN,NaN,...,NaN,NaN,GOOD,apartment,NaN,NaN,1.0,3.0,2,residential_monthly_rent

In [6]:
data.groupby("TypeOfProperty")["Price"].agg([np.mean, np.median, np.max])

/tmp/ipykernel_11523/673286483.py:1: FutureWarning: The provided callable <function mean at 0x7fae5c463920> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  data.groupby("TypeOfProperty")["Price"].agg([np.mean, np.median, np.max])
/tmp/ipykernel_11523/673286483.py:1: FutureWarning: The provided callable <function median at 0x7fae5c3a85e0> is currently using SeriesGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  data.groupby("TypeOfProperty")["Price"].agg([np.mean, np.median, np.max])
/tmp/ipykernel_11523/673286483.py:1: FutureWarning: The provided callable <function max at 0x7fae5c462f20> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  data.groupby("TypeOfProperty")["Price"].agg([np.mean, np.median, np.max])

                         mean    median       max
TypeOfProperty
1               457638.172185  360537.0  22500000
2               308345.723776  274500.0  35000000

In [7]:
data.sort_values("NumberOfFacades", ascending=False)[["Url"]]

                                                                                               Url
60736              https://www.immoweb.be/en/classified/apartment/for-rent/bruxelles/1000/20010883
103993                  https://www.immoweb.be/en/classified/house/for-sale/gembloux/5030/11329216
721                     https://www.immoweb.be/en/classified/house/for-sale/arsimont/5060/10947037
41201              https://www.immoweb.be/en/classified/apartment/for-sale/antwerpen/2100/11460011
108517               https://www.immoweb.be/en/classified/house/for-sale/tielt-winge/3390/11294488
...                                                                                            ...
181728               https://www.immoweb.be/en/classified/apartment/for-sale/lebbeke/9280/10331313
181738  https://www.immoweb.be/en/classified/apartment/for-sale/woluwe-saint-lambert/1200/10330761
181788                    https://www.immoweb.be/en/classified/house/for-sale/aalter/9880/11425357
181791                https://www.immoweb.be/en/classified/apartment/for-sale/brugge/8000/11485038
181792  https://www.immoweb.be/en/classified/apartment/for-rent/woluwe-saint-lambert/1200/11370116

[118714 rows x 1 columns]

In [8]:
data.columns.tolist()

['Url',
 'BathroomCount',
 'BedroomCount',
 'ConstructionYear',
 'Country',
 'District',
 'Fireplace',
 'FloodingZone',
 'Furnished',
 'Garden',
 'GardenArea',
 'Kitchen',
 'LivingArea',
 'Locality',
 'MonthlyCharges',
 'NumberOfFacades',
 'PEB',
 'PostalCode',
 'Price',
 'PropertyId',
 'Province',
 'Region',
 'RoomCount',
 'ShowerCount',
 'StateOfBuilding',
 'SubtypeOfProperty',
 'SurfaceOfPlot',
 'SwimmingPool',
 'Terrace',
 'ToiletCount',
 'TypeOfProperty',
 'TypeOfSale']

In [9]:
data['Openfire'].value_counts()

KeyError: 'Openfire'

In [63]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 115070 entries, 2 to 176905
Data columns (total 21 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Url                115070 non-null  object
 1   Openfire           115070 non-null  bool
 2   Furnished          115070 non-null  bool
 3   Terrace            115070 non-null  bool
 4   Garden             115070 non-null  bool
 5   PropertyId         115070 non-null  int64
 6   TypeOfProperty     115070 non-null  int64
 7   PostalCode         115070 non-null  int64
 8   SubtypeOfProperty  115070 non-null  object
 9   TypeOfSale         115070 non-null  int64
 10  Price              115070 non-null  int64
 11  Kitchen            64857 non-null   object
 12  StateOfBuilding    78622 non-null   object
 13  Heating            65283 non-null   object
 14  Bedrooms           115070 non-null  int64
 15  SurfaceOfGood      56247 non-null   float64
 16  SwimmingPool       115070 non-null  bool
 17  ConstructionYear   66671 non-null   float64
 18  GardenArea         21624 non-null   float64
 19  LivingArea         101377 non-null  float64
 20  NumberOfFacades    74262 non-null   float64
dtypes: bool(5), float64(5), int64(6), object(5)
memory usage: 15.5+ MB

In [64]:
data.isnull().sum()

Url                      0
Openfire                 0
Furnished                0
Terrace                  0
Garden                   0
PropertyId               0
TypeOfProperty           0
PostalCode               0
SubtypeOfProperty        0
TypeOfSale               0
Price                    0
Kitchen              50213
StateOfBuilding      36448
Heating              49787
Bedrooms                 0
SurfaceOfGood        58823
SwimmingPool             0
ConstructionYear     48399
GardenArea           93446
LivingArea           13693
NumberOfFacades      40808
dtype: int64

In [65]:
data.groupby(by =['TypeOfProperty', 'TypeOfSale']).size()

TypeOfProperty  TypeOfSale
1               1             47597
                2              2606
2               1             54882
                2              9985
dtype: int64

In [66]:
data.nunique()

Url                  115070
Openfire                  1
Furnished                 2
Terrace                   2
Garden                    2
PropertyId           115068
TypeOfProperty            2
PostalCode             1220
SubtypeOfProperty        41
TypeOfSale                2
Price                 10295
Kitchen                   8
StateOfBuilding           6
Heating                   7
Bedrooms                 50
SurfaceOfGood          4542
SwimmingPool              2
ConstructionYear        239
GardenArea             1836
LivingArea             1057
NumberOfFacades          15
dtype: int64

In [67]:
data.isnull().sum()

Url                      0
Openfire                 0
Furnished                0
Terrace                  0
Garden                   0
PropertyId               0
TypeOfProperty           0
PostalCode               0
SubtypeOfProperty        0
TypeOfSale               0
Price                    0
Kitchen              50213
StateOfBuilding      36448
Heating              49787
Bedrooms                 0
SurfaceOfGood        58823
SwimmingPool             0
ConstructionYear     48399
GardenArea           93446
LivingArea           13693
NumberOfFacades      40808
dtype: int64

In [68]:
for i in data.columns:
    null_rate = data[i].isnull().sum() / len(data) * 100
    if null_rate > 0:
        print(f"{i} null rate: %{null_rate:.2f}")

Kitchen null rate: %43.64
StateOfBuilding null rate: %31.67
Heating null rate: %43.27
SurfaceOfGood null rate: %51.12
ConstructionYear null rate: %42.06
GardenArea null rate: %81.21
LivingArea null rate: %11.90
NumberOfFacades null rate: %35.46

In [69]:
data.sort_values("Kitchen")

,Url,Openfire,Furnished,Terrace,Garden,PropertyId,TypeOfProperty,PostalCode,SubtypeOfProperty,TypeOfSale,...,Kitchen,StateOfBuilding,Heating,Bedrooms,SurfaceOfGood,SwimmingPool,ConstructionYear,GardenArea,LivingArea,NumberOfFacades
46031,https://www.immoweb.be/en/classified/apartment/for-rent/etterbeek/1040/11473810,False,False,True,False,11473810,2,1040,apartment,2,...,hyper equipped,as new,None,1,NaN,False,NaN,NaN,NaN,2.0
117229,https://www.immoweb.be/en/classified/house/for-sale/evere/1140/11187507,False,False,True,False,11187507,1,1140,house,1,...,hyper equipped,as new,gas,4,64.0,False,1947.0,NaN,182.0,2.0
89416,https://www.immoweb.be/en/classified/apartment/for-sale/westerlo/2260/11309177,False,False,False,False,11309177,2,2260,apartment,1,...,hyper equipped,as new,gas,2,NaN,False,1977.0,NaN,105.0,3.0
42070,https://www.immoweb.be/en/classified/apartment/for-sale/woluwe-saint-lambert/1200/11469267,False,False,True,False,11469267,2,1200,apartment,1,...,hyper equipped,good,None,2,NaN,False,2025.0,NaN,84.0,NaN
117240,https://www.immoweb.be/en/classified/house/for-sale/blaasveld/2830/11187388,False,False,False,False,11187388,1,2830,house,1,...,hyper equipped,None,None,3,369.0,False,2024.0,NaN,293.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176735,https://www.immoweb.be/en/classified/apartment/for-sale/deerlijk/8540/8756251,False,False,True,False,8756251,2,8540,apartment,1,...,None,good,gas,2,NaN,False,2020.0,NaN,112.0,2.0
176760,https://www.immoweb.be/en/classified/apartment/for-sale/trois-ponts/4980/8749786,False,False,False,False,8749786,2,4980,apartment unit,1,...,None,None,gas,3,NaN,False,NaN,NaN,169.0,NaN
176778,https://www.immoweb.be/en/classified/apartment/for-sale/knokke/8300/8746466,False,False,False,False,8746466,2,8300,apartment,1,...,None,as new,None,2,NaN,False,NaN,NaN,157.0,2.0
176821,https://www.immoweb.be/en/classified/apartment/for-rent/brugge/8000/8737969,False,False,False,False,8737969,2,8000,kot,2,...,None,good,None,0,NaN,False,2016.0,NaN,21.0,NaN
176904,https://www.immoweb.be/en/classified/house/for-sale/denderhoutem/9450/10877172,False,False,False,False,10877172,1,9450,mansion,1,...,None,to renovate,None,4,338.0,False,1910.0,NaN,280.0,NaN

In [74]:
data[data["PostalCode"] == False]

,Url,Openfire,Furnished,Terrace,Garden,PropertyId,TypeOfProperty,PostalCode,SubtypeOfProperty,TypeOfSale,...,Kitchen,StateOfBuilding,Heating,Bedrooms,SurfaceOfGood,SwimmingPool,ConstructionYear,GardenArea,LivingArea,NumberOfFacades
28711,https://www.immoweb.be/en/classified/house/for-sale/perla-bonita/0000/7437738,False,False,True,False,7437738,1,0,villa,1,...,installed,good,None,4,0.0,False,2012.0,NaN,120.0,4.0
28712,https://www.immoweb.be/en/classified/house/for-sale/ceiba/00000/7437739,False,False,True,False,7437739,1,0,villa,1,...,installed,good,None,12,1296.0,True,2013.0,NaN,NaN,4.0
28715,https://www.immoweb.be/en/classified/house/for-sale/rio-san-juan/00000/7437737,False,False,False,False,7437737,1,0,villa,1,...,installed,good,None,4,529.0,False,NaN,NaN,290.0,4.0
91572,https://www.immoweb.be/en/classified/apartment/for-rent/gent/0/11297796,False,False,False,False,11297796,2,0,apartment,2,...,None,good,gas,1,NaN,False,NaN,NaN,52.0,NaN
102555,https://www.immoweb.be/en/classified/apartment/for-sale/al-mina-al-siyahi/0/11321866,False,False,True,False,11321866,2,0,apartment,1,...,None,None,None,1,NaN,False,NaN,NaN,NaN,NaN
165487,https://www.immoweb.be/en/classified/apartment/for-sale/leuven/00000/10046544,False,False,False,True,10046544,2,0,apartment,1,...,installed,good,gas,1,NaN,False,NaN,5.0,65.0,2.0

### Drop property with PostalCode False (0) 4 properties outside belgium and 2 properties in Belgium without infos

In [71]:
# data = data[data["PostalCode"] == True]

In [72]:
data

,Url,Openfire,Furnished,Terrace,Garden,PropertyId,TypeOfProperty,PostalCode,SubtypeOfProperty,TypeOfSale,...,Kitchen,StateOfBuilding,Heating,Bedrooms,SurfaceOfGood,SwimmingPool,ConstructionYear,GardenArea,LivingArea,NumberOfFacades
2,https://www.immoweb.be/en/classified/house/for-sale/steendorp/9140/8720603,False,False,True,False,8720603,1,9140,house,1,...,installed,just renovated,gas,3,60.0,False,1940.0,NaN,116.0,2.0
6,https://www.immoweb.be/en/classified/apartment/for-rent/ixelles/1050/8719883,False,True,False,False,8719883,2,1050,flat studio,2,...,hyper equipped,just renovated,gas,8,NaN,False,NaN,NaN,312.0,NaN
8,https://www.immoweb.be/en/classified/house/for-sale/reet/2840/10760048,False,False,False,False,10760048,1,2840,house,1,...,None,None,None,3,158.0,False,2024.0,NaN,150.0,2.0
10,https://www.immoweb.be/en/classified/house/for-sale/bilzen/3740/10759911,False,False,True,False,10759911,1,3740,house,1,...,None,good,None,3,337.0,False,2023.0,NaN,138.0,3.0
13,https://www.immoweb.be/en/classified/house/for-sale/koolskamp/8851/10759812,False,False,True,False,10759812,2,8851,house unit,1,...,None,None,None,3,267.0,False,NaN,NaN,NaN,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176860,https://www.immoweb.be/en/classified/apartment/for-sale/sint-truiden/3800/8727283,False,False,True,False,8727283,2,3800,apartment,1,...,semi equipped,to renovate,gas,2,NaN,False,1967.0,NaN,135.0,2.0
176890,https://www.immoweb.be/en/classified/apartment/for-rent/virton/6760/8724542,False,False,False,False,8724542,2,6760,apartment,2,...,installed,as new,fueloil,2,NaN,False,2015.0,NaN,90.0,2.0
176903,https://www.immoweb.be/en/classified/apartment/for-sale/herentals/2200/20014272,False,False,True,False,20014272,2,2200,ground floor,1,...,semi equipped,None,None,1,NaN,False,2023.0,NaN,52.0,2.0
176904,https://www.immoweb.be/en/classified/house/for-sale/denderhoutem/9450/10877172,False,False,False,False,10877172,1,9450,mansion,1,...,None,to renovate,None,4,338.0,False,1910.0,NaN,280.0,NaN
176905,https://www.immoweb.be/en/classified/apartment/for-sale/vise/4600/10718231,False,False,True,False,10718231,2,4600,apartment unit,1,...,installed,None,gas,2,NaN,False,2024.0,NaN,101.0,3.0

In [97]:
# postal code in Belgium
postal_code = pd.read_excel("zipcodes_num_fr_new.xls")

ImportError: Missing optional dependency 'xlrd'. Install xlrd >= 2.0.1 for xls Excel support Use pip or conda to install xlrd.